### ISSUE TITLE
is nss is already initiatzed, do not initialize it

### ISSUE THREAD

**Issue by letoams** [Rishabh04-02/Libreswan-Opportunistic-IPsec#1]
right now it always runs ipsec initnss

**Comment by Rishabh04-02** [comment]
Yes, But I was unable to find a way to check whether it is initialized or not.
So *temporarily*, I've added a command to initialize it every time.
**I'll find a way to check for it and then will update the code.**

**Comment by Rishabh04-02** [comment]
Issue Resolved.
