### ISSUE TITLE
look at certbot plugin for libreswan that allows working without webserver

### ISSUE THREAD

**Issue by letoams** [Rishabh04-02/Libreswan-Opportunistic-IPsec#10]
is a plugin something that we can use?

would it allow us to get a certifcate issued and renewed without running a apache/nginx webserver"?

**Comment by Rishabh04-02** [comment]
Fixed using `sudo certbot certonly --webroot` [reference](https://certbot.eff.org/docs/using.html#webroot)
used [here](https://github.com/Rishabh04-02/Libreswan-Opportunistic-IPsec/blob/master/generate_certificate#L23)
