### ISSUE TITLE
subcommand could use a "-" in name 

### ISSUE THREAD

**Issue by letoams** [Rishabh04-02/Libreswan-Opportunistic-IPsec#20]
ipsec letgenerate certificatesencrypt 
ipsec letgenerate updatecertificate

that is pretty unreadable. Use certificates-encrypt and update-certificate instead ?

**Comment by bleve** [comment]
ipsec letsencrypt is the command - everything else should be options so starting with --

**Comment by bleve** [comment]
So --generate-certificate and --update-certificate
