### ISSUE TITLE
long command options for ipsec letsencrypt command

### ISSUE THREAD

**Issue by bleve** [Rishabh04-02/Libreswan-Opportunistic-IPsec#21]
There is small inconsistency in usability in letsecrypt command. All of libreswan uses --longoption format for long commands. ipsec letsencrypt now uses -client and -server when those should be --client and --server for consistency.

**Comment by Rishabh04-02** [comment]
Fixed https://github.com/Rishabh04-02/Libreswan-Opportunistic-IPsec/commit/199e7d773a8af943cf41a4e6e0f4bf253a1f0698
