### ISSUE TITLE
ipsec letsencrypt -client should not start ipsec if ipesc wasn't running at the time

### ISSUE THREAD

**Issue by letoams** [Rishabh04-02/Libreswan-Opportunistic-IPsec#22]
ipsec letsencrypt -client should not start ipsec if ipesc wasn't running at the time

the administrator might want to just run it to prepare, but not start ipsec yet.

**Comment by Rishabh04-02** [comment]
Fixed https://github.com/Rishabh04-02/Libreswan-Opportunistic-IPsec/commit/55f451e017cc805300bbb031163e001bebb9297e
