### ISSUE TITLE
server config should not contain someone elses hostname

### ISSUE THREAD

**Issue by letoams** [Rishabh04-02/Libreswan-Opportunistic-IPsec#24]
eg 	leftcert=letsencrypt.libreswan.org

It should perhaps use: leftcert=YourServerDNSName

**Comment by Rishabh04-02** [comment]
Fixed https://github.com/libreswan/libreswan/pull/263/commits/46d01f40c281138729ac639233ef27c9ea37d6b3

~Documentation yet to be updated.~ Documentation updated.
