### ISSUE TITLE
add 0.0.0.0/0 to private-or-clear

### ISSUE THREAD

**Issue by letoams** [Rishabh04-02/Libreswan-Opportunistic-IPsec#25]
when the -client or -server option is given, instead of only adding the IP of letsencrypt.libreswan.org, ALSO add 0.0.0.0/0. Maybe with a comment, so the file content will be:

\# The libreswan letsenccrypt test server - this can be left enabled at all times
193.110.157.131/32
\# Attempt OE IPsec using letsencrypt for the entire Internet - Comment out to disable
0.0.0.0/0

We can enable 0.0.0.0/0 because we use a quick 3s timeout

**Comment by Rishabh04-02** [comment]
Fixed https://github.com/libreswan/libreswan/pull/263/commits/34ee644ecea35819190bd0d8aa92995fe29fe981
